// 스타일 노드 21종 — 온보딩 ③ 취향 픽의 선택지 데이터.
// 출처: PostgreSQL style_nodes + brand_nodes (2026-07-14 스냅샷, 노드↔브랜드 실매핑).
// brandCount = primary 노드 기준, women/men = gender_scope 교집합(unisex 포함).
// sampleBrands* = style_node_confidence 상위 6개 — 온보딩 노드 칩의 서브텍스트/미리보기용.
// 실서비스는 GET /v1/brand-nodes 로 대체 예정 (API 명세서 v1.1).

export type StyleNode = (typeof STYLE_NODES)[number];

export const STYLE_NODES = [
  {"id": 1, "code": "A", "nameKo": "컨템퍼러리 캐주얼", "nameEn": "Contemporary Casual", "brandCount": 394, "womenBrandCount": 187, "menBrandCount": 127, "sampleBrandsWomen": ["ANYTIME LOREAK (애니타임로릭)", "BONNIE CLYDE", "COA NYC", "Dunst", "Grlfrnd", "HommeGirls"], "sampleBrandsMen": ["ANYTIME LOREAK (애니타임로릭)", "BONNIE CLYDE", "CARRER", "Dunst", "Glass Cypress", "Howlin’"]},
  {"id": 2, "code": "B", "nameKo": "프렌치 이펄리스", "nameEn": "French Effortless", "brandCount": 87, "womenBrandCount": 32, "menBrandCount": 9, "sampleBrandsWomen": ["OSPERA", "Isabel Marant Etoile", "IRO Paris", "REQINS", "Maison Kitsuné", "Loulou de Saison"], "sampleBrandsMen": ["Officine Générale", "OSPERA", "Maison Kitsuné", "AMI Paris", "A.P.C.", "Becay"]},
  {"id": 3, "code": "C", "nameKo": "스칸디 미니멀", "nameEn": "Scandi Minimal", "brandCount": 112, "womenBrandCount": 71, "menBrandCount": 36, "sampleBrandsWomen": ["COMME SE-A", "determ;", "Gauchere", "müdule", "Nothing Written", "REMAIN Birger Christensen"], "sampleBrandsMen": ["Gauchere", "müdule", "SONIA CARRASCO", "System", "Norse Projects", "JEANERICA"]},
  {"id": 4, "code": "D", "nameKo": "콰이엇 럭셔리", "nameEn": "Quiet Luxury", "brandCount": 360, "womenBrandCount": 135, "menBrandCount": 57, "sampleBrandsWomen": ["Atlein", "Citizens of Humanity", "ELLISS", "Fane", "HÉROS", "House of Dagmar"], "sampleBrandsMen": ["ALTU", "KARA", "Kota Gushiken", "PONDER.ER", "Thistles", "The Row"]},
  {"id": 5, "code": "E", "nameKo": "모던 프렙", "nameEn": "Modern Prep", "brandCount": 34, "womenBrandCount": 4, "menBrandCount": 10, "sampleBrandsWomen": ["AURALEE", "Sporty & Rich", "Thom Browne", "Subdued"], "sampleBrandsMen": ["Ahluwalia &PaulSmith", "Le PÈRE", "AURALEE", "Fred Perry", "Palmes", "Manors Golf"]},
  {"id": 6, "code": "F", "nameKo": "헤리티지 아메리카나", "nameEn": "Heritage Americana", "brandCount": 178, "womenBrandCount": 25, "menBrandCount": 30, "sampleBrandsWomen": ["PHIPPS", "Dr. Martens", "AGOLDE", "Barbour", "Bode", "Carhartt WIP"], "sampleBrandsMen": ["Deadwood", "PHIPPS", "Uniform Bridge", "Greg Lauren", "Nudie Jeans", "Dr. Martens"]},
  {"id": 7, "code": "G", "nameKo": "재패니즈 워크웨어", "nameEn": "Japanese Workwear", "brandCount": 103, "womenBrandCount": 11, "menBrandCount": 39, "sampleBrandsWomen": ["CCU LEATHER", "NEEDLES", "visvim", "Casey Casey", "Issuethings", "Ernie Palo"], "sampleBrandsMen": ["CCU LEATHER", "Engineered Garments", "NEEDLES", "N.Hoolywood", "visvim", "International Gallery BEAMS"]},
  {"id": 8, "code": "H", "nameKo": "사토리얼 테일러링", "nameEn": "Sartorial Tailoring", "brandCount": 50, "womenBrandCount": 9, "menBrandCount": 29, "sampleBrandsWomen": ["ZEGNA", "TOM FORD", "Ernest W. Baker", "WOOYOUNGMI", "AARON ESH", "MAU SOLEUM"], "sampleBrandsMen": ["Bethany Williams", "Factor's", "ZEGNA", "Brioni", "TOM FORD", "Eidos"]},
  {"id": 9, "code": "I", "nameKo": "NY 뉴프렙 스트릿", "nameEn": "NY New Prep Street", "brandCount": 179, "womenBrandCount": 32, "menBrandCount": 51, "sampleBrandsWomen": ["언더마이카", "About:blank", "Daniëlle Cathari", "DEVEAUX NEW YORK", "PERVERZE", "rag & bone"], "sampleBrandsMen": ["언더마이카", "About:blank", "colbo", "rag & bone", "Saintwoods", "Alexander Wang"]},
  {"id": 10, "code": "J", "nameKo": "스케이트 스트릿", "nameEn": "Skate Street", "brandCount": 125, "womenBrandCount": 29, "menBrandCount": 36, "sampleBrandsWomen": ["BAPE", "Nike", "Vans", "슈프림", "Brain Dead", "Nike Jordan"], "sampleBrandsMen": ["Silas", "BAPE", "AAPE by A Bathing Ape", "Nike", "Vans", "슈프림"]},
  {"id": 11, "code": "K", "nameKo": "아트스쿨 인디 스트릿", "nameEn": "Art-school Indie Street", "brandCount": 207, "womenBrandCount": 100, "menBrandCount": 87, "sampleBrandsWomen": ["써저리", "AVAVAV", "INSCRIRE", "Magliano", "Puppets and Puppets", "SRVC"], "sampleBrandsMen": ["써저리", "ALEXANDER DIGENOVA", "AVAVAV", "HARAGO", "Magliano", "Solitude Studios"]},
  {"id": 12, "code": "L", "nameKo": "럭셔리 스트릿", "nameEn": "Luxury Streetwear", "brandCount": 119, "womenBrandCount": 40, "menBrandCount": 61, "sampleBrandsWomen": ["GREG ROSS", "Pushbutton", "STEFAN COOKE", "A MACHINE", "Off-White", "1017 ALYX 9SM"], "sampleBrandsMen": ["PALMER", "STEFAN COOKE", "TSAU", "Youths in Balaclava", "A MACHINE", "Off-White"]},
  {"id": 13, "code": "M", "nameKo": "다크 아방가르드", "nameEn": "Dark Avant-garde", "brandCount": 75, "womenBrandCount": 32, "menBrandCount": 36, "sampleBrandsWomen": ["Rick Owens", "YOHJI YAMAMOTO", "McQueen", "Noir Kei Ninomiya", "Rick Owens Drkshdw", "BMUET(TE)"], "sampleBrandsMen": ["Rick Owens", "YOHJI YAMAMOTO", "A DICIANNOVEVENTITRE", "McQueen", "Rick Owens Drkshdw", "99%IS-"]},
  {"id": 14, "code": "N", "nameKo": "벨지언 컨셉추얼", "nameEn": "Belgian Conceptual", "brandCount": 70, "womenBrandCount": 43, "menBrandCount": 40, "sampleBrandsWomen": ["AIREI", "Bernhard Willhelm", "Boyarovskaya", "Juun.J", "Niccolo Pasqualetti", "REVENIOMAKER"], "sampleBrandsMen": ["AIREI", "BLUEMARBLE", "CALVINLUO", "Camiel Fortgens", "Juun.J", "REVENIOMAKER"]},
  {"id": 15, "code": "O", "nameKo": "런웨이 익스페리먼탈", "nameEn": "Runway Experimental", "brandCount": 75, "womenBrandCount": 40, "menBrandCount": 38, "sampleBrandsWomen": ["Paula Canovas Del Vas", "Comme des Garçons", "Issey Miyake", "sacai", "UNDERCOVER", "Bao Bao Issey Miyake"], "sampleBrandsMen": ["B1ARCHIVE", "HUGO KREIT", "Comme des Garçons Homme Plus", "sacai", "Craig Green", "Kuboraum"]},
  {"id": 16, "code": "P", "nameKo": "럭셔리 맥시멀리스트", "nameEn": "Luxury Maximalist", "brandCount": 111, "womenBrandCount": 39, "menBrandCount": 16, "sampleBrandsWomen": ["Ichiyo", "Sophia Webster", "Dolce&Gabbana", "Balmain", "16Arlington", "Moschino Jeans"], "sampleBrandsMen": ["Dolce&Gabbana", "Balmain", "Valentino", "Versace", "Valentino Garavani", "Kenzo"]},
  {"id": 17, "code": "Q", "nameKo": "로맨틱 페미닌", "nameEn": "Romantic Feminine", "brandCount": 191, "womenBrandCount": 102, "menBrandCount": 10, "sampleBrandsWomen": ["1CONCEPT", "Grape", "Jenny Fax", "J KOO", "Juliet Johnstone", "Nicklas Skovgaard"], "sampleBrandsMen": ["Vanya Sundari", "VINNY’s", "ARC Object", "KIJUN", "Apartment 1007", "Jijivisha"]},
  {"id": 18, "code": "R", "nameKo": "센슈얼 페미닌", "nameEn": "Sensual Feminine", "brandCount": 178, "womenBrandCount": 98, "menBrandCount": 10, "sampleBrandsWomen": ["BINYA", "DIDU", "DOS SWIM", "Emily Watson", "Miss Sixty", "nastyamasha"], "sampleBrandsMen": ["Versace Underwear", "Dion Lee", "Isa Boulder", "K.NGSLEY", "Alan Crocetti", "Ludovic de Saint Sernin"]},
  {"id": 19, "code": "S", "nameKo": "고프코어 아웃도어", "nameEn": "Gorpcore Outdoor", "brandCount": 190, "womenBrandCount": 56, "menBrandCount": 67, "sampleBrandsWomen": ["EMU Australia", "아크테릭스", "PUMA", "Salomon", "오호스", "Cayl"], "sampleBrandsMen": ["A. A. Spectrum", "아크테릭스", "Arc'teryx", "PUMA", "Salomon", "SOAR Running"]},
  {"id": 20, "code": "T", "nameKo": "이탈리안 테크럭셔리", "nameEn": "Italian Tech-luxury", "brandCount": 30, "womenBrandCount": 10, "menBrandCount": 15, "sampleBrandsWomen": ["Moncler", "Stone Island", "TATRAS", "GR10K", "HELIOT EMIL", "Veilance"], "sampleBrandsMen": ["XLIM", "Moncler", "Stone Island", "TATRAS", "Parajumpers", "BYBORRE"]},
  {"id": 21, "code": "U", "nameKo": "한국 영캐주얼", "nameEn": "Korean Young Casual", "brandCount": 185, "womenBrandCount": 158, "menBrandCount": 61, "sampleBrandsWomen": ["Epingler", "ERA", "MARGESHERWOOD", "그레일즈", "탄산마그네슘", "999휴머니티"], "sampleBrandsMen": ["ERA", "그레일즈", "탄산마그네슘", "999휴머니티", "JACQUES", "OJOS"]},
] as const;
